### ISSUE TITLE
unable to load sounds via SD and web portal or save settings in web portal for v2

### ISSUE THREAD

**Issue by thecolor** [CircuitSetup/Time-Circuits-Display#17] opened 2022-08-31 15:08 UTC
the device either does not recognize the SD card or the web portal is not recognizing the content.
Unable to load sounds via the enter key command instructed either.
unable to save settings in the web portal.  *upon clicking save, nothing changes.

**Comment by CircuitSetup** [comment] 2022-08-31 15:29
I just updated the data directory to remove some files that should not have been there. Please try again with only the files currently in the data directory.

**Comment by thecolor** [comment] 2022-08-31 15:35
I only have the mp3 files on the SD card. Is one of those the wrong file?
I upgraded to v2 yesterday via the web portal and while the web portal loads, the settings don't save anything, so the time is central instead of the PDT I've tried to save and no other changes I make save.

**Comment by CircuitSetup** [comment] 2022-08-31 15:59
beep, and a nmoff2, and nmon2 should not have been in there. 4 ee files were just added. 

When you save everything does the TCD reset?

**Comment by thecolor** [comment] 2022-08-31 16:11
I literally only loaded these files to the root of the SD card and tried that (based on how I was understanding the [instructions](https://github.com/CircuitSetup/Time-Circuits-Display/wiki/9.-Programming-&-Upgrading-the-Firmware-(ESP32)).

beep.mp3
Dtmf-0.mp3
Dtmf-1.mp3
Dtmf-2.mp3
Dtmf-3.mp3
Dtmf-4.mp3
Dtmf-5.mp3
Dtmf-6.mp3
Dtmf-7.mp3
Dtmf-8.mp3
Dtmf-9.mp3
enter.mp3
startup.mp3
timetravel.mp3

should I have loaded the entire DIR "src" or "data"?

The v2 .bin has been loaded via the web portal.

**Comment by thecolor** [comment] 2022-08-31 18:28
ok, so it does seem to reset when I click save, although nothing changes.
I've reloaded all the content referenced to the SD, and the audio section to "copy" is still not present, (in addition to no changes being saved.)  - screenshot attached for the portal I'm seeing.

![webPortal](https://user-images.githubusercontent.com/13891433/187752720-42a9252c-beca-4039-8058-bcbcfb520533.jpg)

**Comment by CircuitSetup** [comment] 2022-08-31 18:38
hum, I'm sorry this is being such a pain to update.

I made a small change in the way it stores data - please try this bin file: https://github.com/CircuitSetup/Time-Circuits-Display/blob/v2/Software/v2.0.0_tcd_firmware_spiffs.bin

Also, do you have a way to view serial output when it is connected to a computer with a USB cable? Via the Arduino IDE or Platformio, maybe?

**Comment by thecolor** [comment] 2022-08-31 18:57
no worries at all... I appreciate the quick updates.

So, the new bin, enabled the web portal to seemingly accept updates, and implied that the audio files were copied, however, upon reboot, only the red, orange and green buttons are lit, the time screens have shut off.

They do seem to work (in that the few times I've rebooted it, the Back To The Future" screen scrolls in, but then all three go blank.

unfortunately, I am not connected to a computer (just power.)

I could, but I may not have the necessary utilities to view things.

If you have instructions, I can try.

**Comment by thecolor** [comment] 2022-08-31 20:43
new discovery...

it was not displaying 'cause I had enabled "Enable fake power switch"
clearly, I was testing and didn't (don't) know how to "power it on"... so I disabled that option.
Now, everything but sound appears to be working.

**Comment by Rudycub23** [comment] 2022-09-01 00:37
> the device either does not recognize the SD card or the web portal is not recognizing the content. Unable to load sounds via the enter key command instructed either. unable to save settings in the web portal. *upon clicking save, nothing changes.

Hello!
I also did an update, both yesterday and today, and had a similar experience to yours with regard to the sound files.  It took me a little bit of time, but I finally figured it out and was successful in loading the sounds. (BTW, I am totally a noob at this; I bought the kit because I thought it was cool, and I only have one other experience with Arduino, so if what I'm telling you here is something that you obviously tried, then please forgive me!)

It would seem that all of the downloaded MP3 files need to be present in the root folder of the SD card with no variations.  I downloaded the files one at a time, and after downloading, apparently all of the files were "renamed", adding their source to the beginning of the file name (Ex: the file "enter" was labeled as "Software_data_src_enter", "startup" was labeled as "Software_data_src_startup", and so forth.).  I figured that after I put the SD card into the slot and not getting it to be recognized was that perhaps the file names were incorrect, so I went back to my computer and removed the source from the name of each file.  After doing this, I put the SD card back into the slot, powered 'er up, and bingo!  (I knew it had worked when I heard the clocks ticking when the opening title showed). Then I was able to access the menu from both the keyboard and the portal, uploaded the sounds, and everything was gold.

Anyway, I hope this helps with your sound issue.

**Comment by CircuitSetup** [comment] 2022-09-01 12:45
@Rudycub23 Sorry it wasn't easier to get working correctly! I'm glad you figured it out though, and thanks for posting your method for getting there.

**Comment by thecolor** [comment] 2022-09-01 14:56
Thanks @Rubycub23  - I will say, the display has stayed lit all night, so that is a good sign... however, I've now noticed that the AM/PM lights are no longer lit - which appears to be related to Enabling "Enable 24-hour clock mode"

I would like the 24-hour clock mode and the AM/PM lit.  I might even prefer the "Present Time" to be 24-hour and the Designation Time and Last Time Departed to not be 24-hour.

As for the sounds, all the files "appear" to be labeled correctly.

Here's a snapshot of the files I'm loading (noting that they are in the root of the SD card.)

![soundFiles](https://user-images.githubusercontent.com/13891433/187945901-c192ac2d-3237-4206-8a44-f7fc838a9f1b.jpg)

**Comment by thecolor** [comment] 2022-09-01 15:08
it's also formatted as the instructions indicated.  (despite formatting it on my MAC.)

![formatting](https://user-images.githubusercontent.com/13891433/187948656-166b47f8-14b7-4e59-94e8-c1c22d35a96f.jpg)

**Comment by thecolor** [comment] 2022-09-01 16:16
so, the most recent try still does not work. I forgot that my MAC adds hidden files to the drive on copying... so, I reformatted on my wife's PC and re-added the same files note above and still no audio.  I will say, it did work prior to the v2 upgrade.

![MacAppended](https://user-images.githubusercontent.com/13891433/187962937-1208ddfa-6a90-4458-bcaf-cc4aad68d608.JPG)

**Comment by realA10001986** [comment] 2022-09-01 19:20
Additional files don't make a difference. 

**ALL** the files of the "data" folder need to be on the SD, unmodified, including the  txt file.

If you don't see the menu "copy sound files" and there is no such option in the Config Portal, one or more files are missing or have been modified.

**Comment by realA10001986** [comment] 2022-09-01 19:30
If you see the "copy audio files" menu (or the respective option in the Config Portal), the SD is recognized and validated, ie the firmware checked if all files are there and unmodified. 

If you can activate the "copy audio files" menu, and there is still no sound, there might be a bug (which I unfortunately can't reproduce here). Will investigate though.

**Comment by Rudycub23** [comment] 2022-09-01 19:39
OK, it looks like you're almost there, but I'm seeing a couple of things in the image above that will need to be corrected (if it hasn't been done already!).

First, those two directories at the top will need to be removed.  Next, it looks to me as if the file names are still not in the correct format; specifically, the dot/period and underscore will need to be removed from the file name of those files.  I think I would do these corrections using the PC if the Mac is adding hidden items, as it would seem that anything extraneous that is added to the root directory will cause it to not work correctly.  Also of note, it looks like you have a couple of duplicate sound files present as well (specifically, "alarm", alarmoff" and "alarmon").  Only one file of each is necessary; duplicates may not make it work, too.

Another thing that I neglected to mention is that the SD card should be inserted with the power OFF; this way, the card can be read when the power is turned on (you have probably done this, but I just want to make sure).

As an aside, I was doing some experimentation with the sound files which I think goes to show how precise and exact things need to be in order for the upload to work correctly.  For example, I wanted to substitute the "enter" sound with the old one from the previous version (I thought it sounded a bit better to me), so I switched them, and when I attempted the upload, it didn't work.  Taking the card back to my PC, I discovered that the file sizes were slightly different (13.0 kb for the old vs. 11.8 kb for the new), so I'm thinking that file size might have something to do with it.  Another thing that I tried was I put the "hour" sound file from the alternate sound directory on the same root directory as the other sounds, and this seemed to also cause the card to not be read.  So it would seem to me that only the files that are in the "data" directory are permitted to be uploaded.

One last thing; I'm not sure if you have seen this, but here is the README file from the fork by A10001986.  It has great step-by-step instructions on how everything works in the set-up menus:

https://github.com/realA10001986/Time-Circuits-Display-A10001986/blob/main/README.md

Again, hope this helps you out.

**Comment by thecolor** [comment] 2022-09-01 19:44
Thanks.  So far, I'm on everyone's same page (have done all the suggested things.)

The file duplicates are standard items a mac adds (like an index) when copying.
They are no longer there (from my latest attempt) and ONLY the audio files with (seeming) proper naming are in the root.

I went to a different computer (my wife's PC) to reformat and re-add the files, so there were no MAC hidden files.
So far, the copy process "seems" to be working, just not playing the sounds on re-boot.

I'll give a poke around the README you mentioned and see if something helps.

Thanks

**Comment by Rudycub23** [comment] 2022-09-01 19:45
> **ALL** the files of the "data" folder need to be on the SD, unmodified, including the txt file.
> 
> If you don't see the menu "copy sound files" and there is no such option in the Config Portal, one or more files are missing or have been modified. (Or the SD is for some reason not recognized)

Oops, looks like you beat me to it!

**Comment by thecolor** [comment] 2022-09-01 19:48
this is the menu item I see when transferring the audio files... does this appear correct?
![installAudio](https://user-images.githubusercontent.com/13891433/187999820-e4a9461b-f8b3-4351-8294-fed1dd8816e1.jpg)

**Comment by realA10001986** [comment] 2022-09-01 19:56
Yes. Write "COPY" into the empty text field to initiate the copy process (which will happen after you click on "Save").

**Comment by realA10001986** [comment] 2022-09-01 20:00
You cannot upload your custom audio files to the flash file system using the "copy audio files" menu / option. This is ONLY for the supplied default sounds (which are very tidily sync'd to the display action).

If you want to "replace" sounds, put the on the SD and leave the card in the slot. They will be played directly from the SD card. If, for instance, a file named "enter.mp3" is found on the SD card, this file is played instead of the default sound in the flash memory. In other words: SD has priority over the internal flash file system.

**Comment by realA10001986** [comment] 2022-09-01 20:22
Don't you have the clock connected to a WiFi network? The actual present time should come through NTP.... (if a time server is configured)

**Comment by Rudycub23** [comment] 2022-09-01 20:29
Bingo!  Glad you got it figured out.

(Of course, no one even _thought_ about the volume being turned down, but there you are...lol! :)

**Comment by thecolor** [comment] 2022-09-01 20:37
now we have this GREAT troubleshooting thread!  :) 


thanks all for the help!!

**Comment by thecolor** [comment] 2022-09-01 21:10
I"d like to point out that (in an effort to resolve this)... I mistook the "0" (zero) key as the "enter" key a couple of times, which caused all three displays to go a little berzerk and at one point, display "malfunction"... then, all three went blank, and not knowing how to fix it, I had to reinstall the v2 bin file to get it back.

Is that an easter egg I don't know how to use?

**Comment by Rudycub23** [comment] 2022-09-01 21:17
Nope; it's the updated, longer time travel mode. At the end of the sequence, you should see the times have moved, just like in the previous version.

As a bonus, you can now "go back" to where you were previously, by holding down "9".

I'm still trying to find the Easter eggs. I'm guessing that they are specific dates that, when entered, will play a particular sound file.

**Comment by thecolor** [comment] 2022-09-01 21:23
@Rudycub23  sorry, not sure I understand.
what is long pressing "0" (zero) doing?

**Comment by realA10001986** [comment] 2022-09-01 21:25
It is triggering a time travel.

Here is detailed manual:
https://github.com/realA10001986/Time-Circuits-Display-A10001986/blob/main/README.md

I made some easter eggs, but they are not included in the version you are using. John for some reason didn't take over those parts of the code.

**Comment by thecolor** [comment] 2022-09-01 21:31
got it.  thank you.
I am noticing that when pressing the "0" (zero) key for two seconds, after (during) the time travel process, it still displays "malfunction" and weird characters and then the top "DESTINATION TIME" goes blank.
*pressing "9" for two seconds does not restore that.
**I have to power it off/restart it to get it to turn back on.  (unless I'm missing a step)

**Comment by thecolor** [comment] 2022-09-01 21:39
out of curiosity, where are these files?
`If the SD card holds files named "key3.mp3" and/or "key6.mp3", these files will be played if you hold the "3"/"6" key for 2 seconds.`

**Comment by realA10001986** [comment] 2022-09-01 21:42
No idea, it works here. The timetravel (and other) sequence(s) are not interruptible by keypad input. (Then again, I am on my code base here, not John's.)

The "3" and "6" keys can play any mp3 named "key3.mp3"/"key6.mp3". They are meant to be provided by the user. Just copy any mp3 (128kbps or less) to the SD card and name it "key3.mp3" or "key6.mp3".

**Comment by Rudycub23** [comment] 2022-09-01 21:49
> I made some easter eggs, but they are not included in the version you are using. John for some reason didn't take over those parts of the code.

Ah, that would explain why I'm not getting anything when I input different dates (again, I'm guessing a particular date triggers the Easter eggs?)

Guess I'll have to reinstall your version and try again!

**Comment by thecolor** [comment] 2022-09-01 21:54
what do you presume the lifespan of the board lights is?

I leave this plugged in 24/7.
I have enabled night mode to turn on from 5-7   - but am curious still.

**Comment by realA10001986** [comment] 2022-09-01 21:56
> > I made some easter eggs, but they are not included in the version you are using. John for some reason didn't take over those parts of the code.
> 
> Ah, that would explain why I'm not getting anything when I input different dates (again, I'm guessing a particular date triggers the Easter eggs?)


Yeah, that's right. But they are well hidden ;)

**Comment by realA10001986** [comment] 2022-09-01 21:58
> what do you presume the lifespan of the board lights is?
> 
> I leave this plugged in 24/7. I have enabled night mode to turn on from 5-7 - but am curious still.

I think no one will be able to answer that with certainty, that's why I bought three ;)

**Comment by realA10001986** [comment] 2022-09-01 21:59
> Guess I'll have to reinstall your version and try again!

Note that you'll need to install the audio files again if you do that. Mine are partly different (and more).

**Comment by thecolor** [comment] 2022-09-01 22:00
ok, is this a different bin version and audio zip?

I'd love t give it a try!

**Comment by realA10001986** [comment] 2022-09-01 22:13
Yeah, all different. But there is no audio zip, you need to download the files one by one, or the entire repository as a zip. I presume you know your ways in github...

**Comment by thecolor** [comment] 2022-09-01 22:14
what's the link to the repository?

**Comment by Rudycub23** [comment] 2022-09-01 22:19
https://github.com/realA10001986/Time-Circuits-Display-A10001986

**Comment by Rudycub23** [comment] 2022-09-01 22:48
OK; I got Easter egg #4...  ;)

**Comment by thecolor** [comment] 2022-09-01 22:54
4 turns night mode on and 5 turns it off.

**Comment by thecolor** [comment] 2022-09-01 22:54
> https://github.com/realA10001986/Time-Circuits-Display-A10001986

this seems to be the one I have installed, so I guess I just need to find whatever is not in the document.  :)

**Comment by thecolor** [comment] 2022-09-01 23:17
I need to change the hour chime on mine, as that is my wife's text message sound.  😁

**Comment by thecolor** [comment] 2022-09-01 23:26
so, this is what happens when I time travel with 0 (zero)... notice the malfunction message.

I have to reboot it to get the top line back.

https://photos.app.goo.gl/ED7MZfp26fEfdVsQA

**Comment by Rudycub23** [comment] 2022-09-02 00:34
It might be possible that your volume control is turned up too much.  I recall seeing that it was all dependent upon how your unit is powered.  Early on in my build, I powered it using the USB cable with an old phone charger that put out 1000mA.  Sometimes, if I had the volume know turned up too high, it would freeze up during a time travel event.  When I finalized my build, I used a wall-wart type transformer that is 5.2 V with 1.6 amps, which worked much better.

Try it again, but turn the volume down to bare minimum, and see how it goes.  If it works, then gradually turn up the volume to where you like it and can get successful time travels at the same time.

**Comment by realA10001986** [comment] 2022-09-02 05:21
Can't watch that video, I only get "your video will be ready soon", but nothing ever happens. 

If the unit freezes during operation at any point, this is definitely a hardware issue. Rubycub23 is probably right; John told me about that issue, too. I never experienced it.

The word "Malfunction" is intended part of the time travel sequence, it does not point to an actual malfunction.

**Comment by CircuitSetup** [comment] 2022-09-02 12:41
> > I made some easter eggs, but they are not included in the version you are using. John for some reason didn't take over those parts of the code.
> 
> Ah, that would explain why I'm not getting anything when I input different dates (again, I'm guessing a particular date triggers the Easter eggs?)
> 
> Guess I'll have to reinstall your version and try again!

They are in the latest .bin, AUG 31 2022 build

**Comment by Rudycub23** [comment] 2022-09-02 12:46
> Can't watch that video, I only get "your video will be ready soon", but nothing ever happens.

Yeah, I couldn't see it either.  I'm just guessing at this point that it's freezing up based upon his description and my prior experience.



> > > I made some easter eggs, but they are not included in the version you are using. John for some reason didn't take over those parts of the code.
> > 
> > 
> > Ah, that would explain why I'm not getting anything when I input different dates (again, I'm guessing a particular date triggers the Easter eggs?)
> > Guess I'll have to reinstall your version and try again!
> 
> They are in the latest .bin, AUG 31 2022 build

Yes; I was able to figure out the fourth one ;).  Now on to the other three (I like a good puzzle, but I think those are going to be a long haul to figure out!).

**Comment by CircuitSetup** [comment] 2022-09-02 12:47
> It might be possible that your volume control is turned up too much. I recall seeing that it was all dependent upon how your unit is powered. Early on in my build, I powered it using the USB cable with an old phone charger that put out 1000mA. Sometimes, if I had the volume knob turned up too high, it would freeze up during a time travel event. When I finalized my build, I used a wall-wart type transformer that is 5.2 V with 1.6 amps, which worked much better.
> 
> Try it again, but turn the volume down to bare minimum, and see how it goes. If it works, then gradually turn up the volume to where you like it and can get successful time travels at the same time.

Yes, this can still happen if you're not connected to a WiFi network, and the sound is nearly all the way up. I'm guessing this is what is happening with @thecolor's display. The only way it would be a problem with the Dest. Time display is if certain characters or LEDs are not lighting up. I can't see the video either, but if the other displays are lit, but the LED's are not blinking for the seconds on the other displays, then the ESP32 "browned out" (because it didn't get enough power) and froze.

**Comment by CircuitSetup** [comment] 2022-09-02 12:50
> > > I made some easter eggs, but they are not included in the version you are using. John for some reason didn't take over those parts of the code.
> > 
> > 
> > Ah, that would explain why I'm not getting anything when I input different dates (again, I'm guessing a particular date triggers the Easter eggs?)
> 
> Yeah, that's right. But they are well hidden ;)

uh, yeah they are! By time I remembered my bitwise operators, and started counting bits, I ran out of time and gave up. haha

**Comment by thecolor** [comment] 2022-09-02 14:34
surprised google is not done processing the video by now.
regardless, I've turned the audio all the way down with the same results.

Does the SW sound act in the background (regardless of the HW sound?)

Since my sound problem was it being switched to SW sound, I wonder if it is to high (even though I changed it back to HW sound.)

**Comment by realA10001986** [comment] 2022-09-02 14:52
No, SW means that the software ignores the pot and sets the volume itself.

The SW volume level does not matter for the known power issue with the pot.

That video could really bring some more light....

**Comment by thecolor** [comment] 2022-09-02 15:05
ok, since the googs is being stupid, I uploaded it to the tube: https://youtu.be/0edFYNtI5Pw

**Comment by CircuitSetup** [comment] 2022-09-02 15:20
> ok, since the googs is being stupid, I uploaded it to the tube: https://youtu.be/0edFYNtI5Pw
> 
> so, this happens regardless of audio being on or off.

Thanks for uploading it. I honestly haven't seen that happen before with a display. I noted that it is flickering more than the other displays, like there is something wrong with it. I'll get a new display in the mail to you. Sorry it took so long to diagnose!

**Comment by thecolor** [comment] 2022-09-02 15:26
thanks.

**Comment by thecolor** [comment] 2022-09-02 16:09
oh, no... my "human" eyes can't see the flicker at all... yes, I totally thought that was just the video... and potential angle of filiming.

That said, I am using a Samsung wall-wart:
Adaptive Fast Charging:
Output: 9.0V --- 1.67A or 5.0V --- 2.0A

The hub is for my 'puter(s)... I have seven sitting around my desk.  ;)
I'm a *nix geek... so I tinker a lot.
Plugging it into one of the ports, (which is coming from the Mac port) appears to not be enough power to keep it running... it gets partly through the boot and then reboots.

I'll see if I can find a smaller powered wall-wart

**Comment by thecolor** [comment] 2022-09-02 16:20
well, I found some REALLY old wall-warts in a box...
one is an output of 1A, the other is an output of 805mA and they still end up with the same result(s).  :/

**Comment by CircuitSetup** [comment] 2022-09-02 16:26
I'm betting something is wrong with either the diode (D1) or the main IC on the back of the display PCB. It could be the wire, but I doubt it since it works initially.

**Comment by thecolor** [comment] 2022-09-02 16:35
is it something I can troubleshoot?

**Comment by CircuitSetup** [comment] 2022-09-02 17:32
> I think I set it up correctly... didn't seem that challenging. you tell me. :D

I don't see anything physically wrong in the picture, but it could be as simple as a cold solder joint. You do have displays that I assembled by hand, so that's more than likely part of the issue 😅

**Comment by thecolor** [comment] 2022-09-02 17:50
I'm not an expert, but it was simple to put together and I would say, very well made!
stuff happens.  no human or electronic is perfect.  :)

**Comment by CircuitSetup** [comment] 2022-09-02 19:56
> I'm not an expert, but it was simple to put together and I would say, very well made! stuff happens. no human or electronic is perfect. :)

Thanks for understanding! I try :)

**Comment by CircuitSetup** [comment] 2022-09-05 19:12
Closing this - reopen if necessary

**Closed by CircuitSetup** 2022-09-05 19:12 UTC

**Comment by thecolor** [comment] 2022-09-06 17:13
The new red board fixed the problem.
Do you want me to send back the old one to try and troubleshoot it?
